### ISSUE TITLE
Erro ao gerar o certificado

### ISSUE THREAD

**Issue by jhefinfulll** [davidherney/moodle-mod_simplecertificate#4]
Exceção - Failed opening required '[dirroot]/lib/horde/framework/Horde/Support/Uuid.php' (include_path='[dirroot]/lib/pear:.:/opt/cpanel/ea-php81/root/usr/share/pear')

este erro foi relatado, aparentemente é o modulo horde que não existe mais no cpanel e está gerando a mensagem de erro.

**Comment by jhefinfulll** [comment]
Consegui resolver este item colocando a pasta Horde de uma versão antiga na versão atual do moodle 4.4 porém os certificados emitidos não são mais listados só da para gerar o certificado.

**Comment by atilasilvalima** [comment]
Tenho Moodle na versão 4.2 onde o Simple Certificate funciona sem problemas e o /lib/horde está instalado, parece que o horde instala junto com outro plugin que estou procurando

**Comment by davidherney** [comment]
Please do not use this page, now I will be providing support on the original project site: https://github.com/bozoh/moodle-mod_simplecertificate

Gracias

Saludos
